In [1]:
import torch
import numpy as np
#torch will be reliant on the np datastructure for tensors

#We want to initialise our tensor by offering data to a numpy array and then parsing that array into torch

data = [[1, 2, 3],[3, 4, 5], [2, 2, 1],[5, 2, 3]]
#we could do torch_data = torch.tensor(data) this is more direct
# more often that not though our data will be in a numpy array

np_a = np.array(data)
tensor_np = torch.from_numpy(np_a) #good
#2

#we can make a shape and datatype like tensor from another tensor
datashapeclone = torch.ones_like(tensor_np) #will be filled with 1's
#random clone 
datashapeclone_rand = torch.rand_like(tensor_np, dtype = torch.float)


In [4]:
print(datashapeclone_rand)
print(tensor_np)
#the chape of these tensors are all 4 by 3
#so the tensor is a shaped object that holds our data for ML
print(f"Shape of tensor: {tensor_np.shape}")
print(f"Datatype of tensor: {tensor_np.dtype}")
print(f"Device tensor is stored on: {tensor_np.device}") #this is just getting tensor info

tensor([[0.7639, 0.1777, 0.0180],
        [0.0364, 0.7276, 0.8171],
        [0.9033, 0.3476, 0.6448],
        [0.5023, 0.7129, 0.1092]])
tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 2, 1],
        [5, 2, 3]], dtype=torch.int32)
Shape of tensor: torch.Size([4, 3])
Datatype of tensor: torch.int32
Device tensor is stored on: cpu


In [6]:
# we want to check that our GPU is available for our tensor operations 
print(torch.cuda.is_available())
if torch.cuda.is_available():
  tensor_np = tensor_np.to('cuda')
  #This will check if cuda is available and then move our tensor to cuda if so
  # avoids a running error when cuda is not available 

True


In [7]:
print(f"Device tensor is stored on: {tensor_np.device}")
#Our tensor should now be stored on Cuda meaning GPU is accessable 

Device tensor is stored on: cuda:0


In [8]:
t1 = torch.cat([tensor_np, tensor_np], dim=1)
print(t1)
#notice how this will combine tensors along one dimension
#we can also just STACK these 

tensor([[1, 2, 3, 1, 2, 3],
        [3, 4, 5, 3, 4, 5],
        [2, 2, 1, 2, 2, 1],
        [5, 2, 3, 5, 2, 3]], device='cuda:0', dtype=torch.int32)


# Extra Notes
Tensors can be multiplied (look up when needed)
We can also calculate matrix multiplication if needed (tensor.matmul(tensor.T2))

We can convert our tensor back to nump with T1.numpy()
Remember from_numpy is numpy to tensor

In [10]:
print(t1, "\n")
t1.add_(3)
print(t1)
#This will add 3 TO EVERY DATAPOINT WITHIN TENSOR

tensor([[4, 5, 6, 4, 5, 6],
        [6, 7, 8, 6, 7, 8],
        [5, 5, 4, 5, 5, 4],
        [8, 5, 6, 8, 5, 6]], device='cuda:0', dtype=torch.int32) 

tensor([[ 7,  8,  9,  7,  8,  9],
        [ 9, 10, 11,  9, 10, 11],
        [ 8,  8,  7,  8,  8,  7],
        [11,  8,  9, 11,  8,  9]], device='cuda:0', dtype=torch.int32)
